[tasks.run-dynamodb-local]
command = "docker"
args = ["compose", "up", "-d"]

[tasks.build]
command = "mold"
args = ["-run", "cargo", "build"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["build-local", "run-dynamodb-local"]
