[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[env.development]
RUST_LOG = "debug"
RUST_BACKTRACE = 1
RUST_LOG_STYLE = "always"
DYNAMODB_LOCAL_PORT = 28000
DYNAMODB_ADMIN_PORT = 28001

[tasks.install-tools]
script = '''
#!/usr/bin/env bash
set -eu

# install formatters for this project
npm install

cp ./.env-template ./.env
'''

[tasks.setup-local]
script = '''
#!/usr/bin/env bash
set -eu

docker compose -p bookshelf -f ./local/compose.yml up -d
sleep 3
./local/create-table.sh
echo "dynamodb-admin listening on http://localhost:${DYNAMODB_ADMIN_PORT}"
'''

[tasks.destroy-local]
script = '''
docker compose -p bookshelf -f ./local/compose.yml down --volumes --remove-orphans
'''

[tasks.lint]
description = "Run linters"
script = '''
export PATH="${CARGO_MAKE_WORKING_DIRECTORY}/node_modules/.bin:$PATH"
cargo +nightly fmt --all -- --check
dprint check --config ./fmt/.dprint.json
prettier --check . \
    --config ./fmt/.prettierrc.toml \
    --ignore-path ./fmt/.prettierignore

cargo +nightly clippy --all-targets --all-features -- -D warnings -D clippy::all
'''

[tasks.fmt]
script = '''
export PATH="${CARGO_MAKE_WORKING_DIRECTORY}/node_modules/.bin:$PATH"

# format Rust code
cargo +nightly fmt --all

# format other files
dprint fmt --incremental=false --config ./fmt/.dprint.json
prettier --write . \
    --config ./fmt/.prettierrc.toml \
    --ignore-path ./fmt/.prettierignore \
    > /dev/null
'''

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["fmt"]

[tasks.build-release]
extend = "build"
args = ["build", "--release"]

[tasks.publish-local]
script = '''
APP_NAME=$(cat ./Cargo.toml \
| docker run -i --rm ghcr.io/tomwright/dasel:latest -r toml 'package.name' \
| sed "s/^'//;s/'$//")
docker build \
    --build-arg APP_NAME=$APP_NAME \
    -t $APP_NAME:latest \
    --progress=plain \
    .
'''

[tasks.run]
env_files = [{ path = "./.env" }]
command = "cargo"
args = ["run"]
dependencies = ["fmt"]
watch = { watch = ["./Cargo.toml", "./src"] }
