name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set Up
        run: |
          rustup toolchain install nightly --profile minimal --component rustfmt --component clippy
          cargo install --force cargo-make
          makers install-tools
      - name: Lint
        run: makers lint
      - name: Run tests
        run: cargo test --release
      - name: Build
        run: cargo build --release
